// AUTO-GENERATED FILE
// This file is automatically generated from content/ folder
// DO NOT EDIT MANUALLY - Your changes will be overwritten
// Last generated: 2025-12-14T23:47:40.554Z

interface MockCollection {
  [key: string]: any[];
}

// In-memory data store populated from CMS content
const mockDataStore: MockCollection = {
  "readymadeprojects": [
    {
      "projectName": "E-Commerce Website",
      "description": "A complete e-commerce solution with shopping cart and payment integration. Perfect for businesses looking to establish an online presence with full e-commerce capabilities.",
      "category": "Web Development",
      "price": 999,
      "techStack": "React, Node.js, MongoDB, Express, Stripe",
      "screenshot1": "/placeholder-project-1.jpg",
      "screenshot2": "/placeholder-ecommerce-2.jpg",
      "features": "|",
      "deliverables": "Complete source code, documentation, deployment guide, 30 days support",
      "demoVideoLink": "https://youtube.com/demo",
      "isFeatured": true,
      "published": true,
      "createdDate": "2024-01-15T00:00:00.000Z",
      "_id": "projects_ecommerce-website",
      "_createdDate": "2024-01-15T00:00:00.000Z",
      "_updatedDate": "2025-12-14T23:47:40.550Z",
      "featuresArray": [
        "|"
      ]
    },
    {
      "projectName": "Portfolio Website",
      "description": "Modern portfolio website for creative professionals. Showcase your work with a stunning, responsive design that makes a lasting impression.",
      "category": "Web Development",
      "price": 499,
      "techStack": "Astro, React, Tailwind CSS, TypeScript",
      "screenshot1": "/placeholder-project-2.jpg",
      "screenshot2": "/placeholder-portfolio-2.jpg",
      "features": "|",
      "deliverables": "Complete source code, customization guide, free updates for 3 months",
      "demoVideoLink": [],
      "isFeatured": false,
      "published": true,
      "createdDate": "2024-01-20T00:00:00.000Z",
      "_id": "projects_portfolio-website",
      "_createdDate": "2024-01-20T00:00:00.000Z",
      "_updatedDate": "2025-12-14T23:47:40.551Z",
      "featuresArray": [
        "|"
      ]
    }
  ],
  "customprojectrequests": [],
  "faq": [
    {
      "question": "How long does it take to complete a project?",
      "answer": "Project timelines vary depending on complexity. Typically, projects take 2-8 weeks.",
      "order": 2,
      "published": true,
      "_id": "faq_project-timeline",
      "_createdDate": "2025-12-14T23:47:40.552Z",
      "_updatedDate": "2025-12-14T23:47:40.552Z"
    },
    {
      "question": "What services do you offer?",
      "answer": "We offer web development, mobile app development, and custom software solutions.",
      "order": 1,
      "published": true,
      "_id": "faq_what-services",
      "_createdDate": "2025-12-14T23:47:40.552Z",
      "_updatedDate": "2025-12-14T23:47:40.552Z"
    }
  ],
  "howitworkssteps": [
    {
      "title": "Choose a Project",
      "description": "Browse our ready-made projects or request a custom solution",
      "order": 1,
      "icon": "search",
      "published": true,
      "_id": "steps_choose-project",
      "_createdDate": "2025-12-14T23:47:40.552Z",
      "_updatedDate": "2025-12-14T23:47:40.552Z"
    },
    {
      "title": "Customize & Order",
      "description": "Customize the project to your needs and place your order",
      "order": 2,
      "icon": "settings",
      "published": true,
      "_id": "steps_customize-order",
      "_createdDate": "2025-12-14T23:47:40.552Z",
      "_updatedDate": "2025-12-14T23:47:40.552Z"
    },
    {
      "title": "Get Your Project",
      "description": "Receive your completed project and launch it",
      "order": 3,
      "icon": "rocket",
      "published": true,
      "_id": "steps_get-project",
      "_createdDate": "2025-12-14T23:47:40.553Z",
      "_updatedDate": "2025-12-14T23:47:40.553Z"
    }
  ],
  "clienttestimonials": [
    {
      "clientName": "John Doe",
      "company": "Tech Solutions Inc",
      "testimonial": "Excellent work! Very professional and delivered on time.",
      "rating": 5,
      "published": true,
      "_id": "testimonials_john-doe",
      "_createdDate": "2025-12-14T23:47:40.553Z",
      "_updatedDate": "2025-12-14T23:47:40.553Z"
    }
  ],
  "developerprofiles": [
    {
      "name": "Developer Team",
      "role": "Full Stack Developers",
      "bio": "Experienced team of developers specializing in modern web technologies",
      "skills": [
        "React",
        "Node.js",
        "TypeScript",
        "Astro",
        "MongoDB"
      ],
      "published": true,
      "_id": "developers_dev-team",
      "_createdDate": "2025-12-14T23:47:40.553Z",
      "_updatedDate": "2025-12-14T23:47:40.553Z"
    }
  ]
};

// Initialize with CMS-managed data
export const initializeMockData = () => {
  console.log('✅ Mock data initialized from CMS content');
  console.log('   - Projects:', mockDataStore.readymadeprojects.length);
  console.log('   - FAQ:', mockDataStore.faq.length);
  console.log('   - Testimonials:', mockDataStore.clienttestimonials.length);
  console.log('   - Steps:', mockDataStore.howitworkssteps.length);
  console.log('   - Developers:', mockDataStore.developerprofiles.length);
};

export const getMockCollection = (collectionId: string) => {
  if (!mockDataStore[collectionId]) {
    mockDataStore[collectionId] = [];
  }
  return mockDataStore[collectionId];
};

export const setMockCollection = (collectionId: string, data: any[]) => {
  mockDataStore[collectionId] = data;
};

export { mockDataStore };
