// AUTO-GENERATED FILE
// This file is automatically generated from content/ folder
// DO NOT EDIT MANUALLY - Your changes will be overwritten
// Last generated: 2025-12-14T22:01:33.057Z

interface MockCollection {
  [key: string]: any[];
}

// In-memory data store populated from CMS content
const mockDataStore: MockCollection = {
  "readymadeprojects": [
    {
      "title": "E-Commerce Website",
      "description": "A complete e-commerce solution with shopping cart and payment integration",
      "price": 999,
      "category": "Web Development",
      "image": "/placeholder-project-1.jpg",
      "features": [
        "Responsive Design",
        "Payment Gateway",
        "Admin Dashboard",
        "Product Management",
        "Order Tracking"
      ],
      "published": true,
      "createdDate": "2024-01-15T00:00:00.000Z",
      "_id": "projects_ecommerce-website",
      "_createdDate": "2024-01-15T00:00:00.000Z",
      "_updatedDate": "2025-12-14T22:01:33.042Z"
    },
    {
      "title": "Portfolio Website",
      "description": "Modern portfolio website for creative professionals",
      "price": 499,
      "category": "Web Development",
      "image": "/placeholder-project-2.jpg",
      "features": [
        "Modern Design",
        "Contact Form",
        "Gallery",
        "Blog Integration",
        "SEO Optimized"
      ],
      "published": true,
      "createdDate": "2024-01-20T00:00:00.000Z",
      "_id": "projects_portfolio-website",
      "_createdDate": "2024-01-20T00:00:00.000Z",
      "_updatedDate": "2025-12-14T22:01:33.054Z"
    }
  ],
  "customprojectrequests": [],
  "faq": [
    {
      "question": "How long does it take to complete a project?",
      "answer": "Project timelines vary depending on complexity. Typically, projects take 2-8 weeks.",
      "order": 2,
      "published": true,
      "_id": "faq_project-timeline",
      "_createdDate": "2025-12-14T22:01:33.055Z",
      "_updatedDate": "2025-12-14T22:01:33.055Z"
    },
    {
      "question": "What services do you offer?",
      "answer": "We offer web development, mobile app development, and custom software solutions.",
      "order": 1,
      "published": true,
      "_id": "faq_what-services",
      "_createdDate": "2025-12-14T22:01:33.055Z",
      "_updatedDate": "2025-12-14T22:01:33.055Z"
    }
  ],
  "howitworkssteps": [
    {
      "title": "Choose a Project",
      "description": "Browse our ready-made projects or request a custom solution",
      "order": 1,
      "icon": "search",
      "published": true,
      "_id": "steps_choose-project",
      "_createdDate": "2025-12-14T22:01:33.055Z",
      "_updatedDate": "2025-12-14T22:01:33.055Z"
    },
    {
      "title": "Customize & Order",
      "description": "Customize the project to your needs and place your order",
      "order": 2,
      "icon": "settings",
      "published": true,
      "_id": "steps_customize-order",
      "_createdDate": "2025-12-14T22:01:33.056Z",
      "_updatedDate": "2025-12-14T22:01:33.056Z"
    },
    {
      "title": "Get Your Project",
      "description": "Receive your completed project and launch it",
      "order": 3,
      "icon": "rocket",
      "published": true,
      "_id": "steps_get-project",
      "_createdDate": "2025-12-14T22:01:33.056Z",
      "_updatedDate": "2025-12-14T22:01:33.056Z"
    }
  ],
  "clienttestimonials": [
    {
      "clientName": "John Doe",
      "company": "Tech Solutions Inc",
      "testimonial": "Excellent work! Very professional and delivered on time.",
      "rating": 5,
      "published": true,
      "_id": "testimonials_john-doe",
      "_createdDate": "2025-12-14T22:01:33.056Z",
      "_updatedDate": "2025-12-14T22:01:33.056Z"
    }
  ],
  "developerprofiles": [
    {
      "name": "Developer Team",
      "role": "Full Stack Developers",
      "bio": "Experienced team of developers specializing in modern web technologies",
      "skills": [
        "React",
        "Node.js",
        "TypeScript",
        "Astro",
        "MongoDB"
      ],
      "published": true,
      "_id": "developers_dev-team",
      "_createdDate": "2025-12-14T22:01:33.056Z",
      "_updatedDate": "2025-12-14T22:01:33.056Z"
    }
  ]
};

// Initialize with CMS-managed data
export const initializeMockData = () => {
  console.log('✅ Mock data initialized from CMS content');
  console.log('   - Projects:', mockDataStore.readymadeprojects.length);
  console.log('   - FAQ:', mockDataStore.faq.length);
  console.log('   - Testimonials:', mockDataStore.clienttestimonials.length);
  console.log('   - Steps:', mockDataStore.howitworkssteps.length);
  console.log('   - Developers:', mockDataStore.developerprofiles.length);
};

export const getMockCollection = (collectionId: string) => {
  if (!mockDataStore[collectionId]) {
    mockDataStore[collectionId] = [];
  }
  return mockDataStore[collectionId];
};

export const setMockCollection = (collectionId: string, data: any[]) => {
  mockDataStore[collectionId] = data;
};

export { mockDataStore };
